#!/bin/sh
#
# processes and installs git repo in polly controller

set -e
set -x

echo post-update... "${1}"

if git show-ref "${1}"
then
  git symbolic-ref HEAD "${1}"
  git update-server-info

  if [ -e /usr/local/bin/polly ];
  then
    TMPCHECKOUT=/polly-safe/tmp/$(mktemp -d)/$(basename $(pwd))
    mkdir -p $(dirname ${TMPCHECKOUT})
    git clone -l . ${TMPCHECKOUT}
    cd ${TMPCHECKOUT}
    unset GIT_DIR

    #TODO: !!!
    #polly build --in-cluster


    polly test


    #TODO: !!!
    #ls -l

    export GIT_DIR="."
  fi
fi

echo ... post-update
