#!/bin/sh
#
# processes and installs git repo in polly controller

set -e
set -x

echo post-update... "${1}"

if git show-ref "${1}"
then
  git symbolic-ref HEAD "${1}"
  git update-server-info

  #TODO: safe to assume polly cli installed in ENV?
  if [ -e /usr/local/bin/polly ];
  then
    #polly-safe
    TMPCHECKOUT=/polly/safe/tmp/$(mktemp -d)/$(basename $(pwd))
    mkdir -p $(dirname ${TMPCHECKOUT})
    git clone -l . ${TMPCHECKOUT}
    cd ${TMPCHECKOUT}
    unset GIT_DIR

    #GENERATED_CI=$(polly continuous)
    #if [ $? -eq 0 ]; then
    #  bash -x -e -c "${GENERATED_CI}" &
    #  wait
    #fi
    echo testing for bad git defunct

    export GIT_DIR="."
  fi
fi

echo ... post-update
