#!/usr/bin/env ruby

@base = image {
  stage "base", "ghcr.io/unhookd/polly:3.0-rc1@sha256:8984c2a507669c8ee53783df68d836b5943afb345f7fc26cbdc6837211a99b94"
  #stage "base", "ghcr.io/unhookd/polly:3.0-rc1"
  #stage "base", "ubuntu:jammy-20220421"

  root

  env "DEBIAN_FRONTEND" => "noninteractive",
      "LC_ALL" => "C.UTF-8",
      "LANG" => "en_US",
      "LANGUAGE" => "en_US",
      "ACCEPT_EULA" => "y"

  group(121, "alpha")
  group(123, "tau")
  group(134, "beta")
  group(999, "docker")
  group(1000, "theta")
  group(1001, "zeta")

  useradd(1000, "app", "alpha,beta,docker,theta,zeta,tau")
  useradd(1001, "runner", "alpha,beta,docker,theta,zeta,tau")

  apt %w{locales locales-all}

  run %q{test -e /usr/lib/locale/locale-archive || ((locale-gen --purge en_US); (echo -e "LANG=$LANG\nLANGUAGE=$LANGUAGE\n" | tee /etc/default/locale); (locale-gen $LANGUAGE); (dpkg-reconfigure locales))}

  apt %w{vim git curl apt-transport-https aptitude ca-certificates apt-utils software-properties-common docker.io build-essential libyaml-dev ruby3* libruby3* ruby-bundler rubygems-integration rake amazon-ecr-credential-helper}

  run %q{curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add}
  run %q{apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"}
  apt %w{kubectl}

  run %q{usermod -a -G $(grep docker /etc/group | cut -d: -f3) app}
  run %q{usermod -a -G $(grep docker /etc/group | cut -d: -f3) runner}
}

# image declares container artifacts
@gem = image {
  stage "gem", @base.stage

  root

  run %q{mkdir -p /polly/safe/git /polly/safe/run /polly/safe/tmp /polly/app /app /__w/polly/polly}
  run %q{chown -R app.alpha /home/app /polly /app /__w/polly/polly}
  run %q{chown -R app /home/app /polly /app /__w/polly/polly}

  #TODO: workdir module
  command("WORKDIR") {
    "/__w/polly/polly"
  }

  run %q{chown -R app /home/app}

  #TODO: more prototype-z detection
  command("COPY") {
    "--chown=app polly.gemspec VERSION /__w/polly/polly/"
  }

  command("COPY") {
    "--chown=app Thorfile /__w/polly/polly/"
  }

  command("COPY") {
    "--chown=app config /__w/polly/polly/config/"
  }

  command("COPY") {
    "--chown=app lib /__w/polly/polly/lib"
  }

  command("COPY") {
    "--chown=app bin /__w/polly/polly/bin"
  }

  command("COPY") {
    "--chown=app doc /__w/polly/polly/doc"
  }

  #app
  #run %q{git config --global user.email "you@example.com"}
  #run %q{git config --global user.name "Your Name"}
  #run %q{gem build polly.gemspec -o polly-latest.gem}

  run %q{su app -s /bin/bash -c 'cd /__w/polly/polly && gem build polly.gemspec -o polly-latest.gem'}
}

# final bits are just the .gem install as if on end-user box
@deploy = image {
  stage "deploy", @base.stage

  app

  command("WORKDIR") {
    "/home/app"
  }

  command("COPY") {
    "--chown=app --from=gem /__w/polly/polly/polly-latest.gem /__w/polly/polly/polly-latest.gem"
  }

  root

  run %q{gem install --no-document --minimal-deps /__w/polly/polly/polly-latest.gem && grep -Rn '\.gem\.' /var/lib 2>/dev/null | cut -d: -f1 | sort | uniq | xargs -I{} rm {} && rm /__w/polly/polly/polly-latest.gem}

  #command("COPY") {
  #  "--chown=app Pollyfile /__w/polly/polly/"
  #}

  ##app
  ##run %q{cd /polly/app && polly generate > Dockerfile}
  #run %q{su app -s /bin/bash -c 'cd /__w/polly/polly && polly generate > Dockerfile'}
}

description("For pollyci")

#workflow_image = "ghcr.io/unhookd/polly:3.0-rc1"
workflow_image = "polly:latest"

@plain_workflow = plan {
  job("primary",
    [{"image"=>workflow_image}],
    [
      {"run"=>{"name"=>"demo","command"=>"echo DEMO!!!!"}},
      {"run"=>{"name"=>"config","command"=>"bundle config set --local path vendor/bundle"}},
      {"run"=>{"name"=>"bundler","command"=>"bundle install"}},
      {"run"=>{"name"=>"rspec","command"=>"bundle exec rspec"}}
    ],{},"/home/app/polly"
  )
}

@gitch_pipeline = continuous {
  #publish @bootstrap_artifact
  test @plain_workflow
}
