---
workflows:
  version: 2
  polly:
    jobs:
    - primary:
        requires: []
version: 2
jobs:
  primary:
    working_directory: "/home/app/polly"
    steps:
    - checkout
    - run:
        name: primary
        command: |-
          echo BEGIN bundler
          bundle install --path=vendor/bundle --with=development
          echo END bundler

          echo BEGIN rspec
          bundle exec rspec
          echo END rspec
    docker:
    - image: ghcr.io/unhookd/polly:3.0-rc1
