workflows:
  version: 2
  build:
    jobs:
    - bootstrap
    - primary:
        requires:
        - bootstrap

defaults: &defaults
  working_directory: /home/app/current
  environment: &environment_defaults
    CUSTOM: "settings"
  docker:
    - image: &build_image ubuntu:latest

version: 2
jobs:
  bootstrap:
    docker:
      - image: &build_image ubuntu:latest
    steps:
      - run:
          name: bootstrap
          command: |
            apt-

  primary:
    <<: *defaults
    steps:
      - run:
          name: rspec
          command: |
            bundle exec rspec
