---
workflows:
  version: 2
  polly:
    jobs:
    - bootstrap:
        requires: []
    - primary:
        requires:
        - bootstrap
version: 2
jobs:
  bootstrap:
    working_directory: "/home/app/polly"
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.12
    - run:
        name: bootstrap
        command: |2

          polly version
    docker:
    - image: ghcr.io/unhookd/polly:3.0-rc1
      user: root
  primary:
    working_directory: "/home/app/polly"
    steps:
    - checkout
    - run:
        name: primary
        command: |2

          echo bundle install --path=vendor/bundle --with=development
          echo bundle exec rspec
    docker:
    - image: ghcr.io/unhookd/polly:3.0-rc1
