---
workflows:
  version: 2
  polly:
    jobs:
    - primary:
        requires: []
version: 2
jobs:
  primary:
    working_directory: "/home/app/polly"
    steps:
    - checkout
    - run:
        name: primary
        command: |-
          #echo DEMO!!!! 222222 UPDTE
          #bundle config set --local path vendor/bundle
          #bundle install
          #bundle exec rspec
    docker:
    - image: ghcr.io/unhookd/polly:3.0-rc1
