---
workflows:
  version: 2
  polly:
    jobs:
    - bootstrap:
        requires: []
    - primary:
        requires:
        - bootstrap
version: 2
jobs:
  bootstrap:
    working_directory: "/home/app/current"
    steps:
    - checkout
    - setup_remote_docker:
        version: 19.03.12
    - run:
        name: bootstrap
        command: |2

          echo BEGIN bootstrap

          apt-get update; apt-get install -y locales locales-all; apt-get clean; rm -rf /var/lib/apt/lists/*
          dpkg-reconfigure locales
          apt-get update; apt-get install -y git curl apt-transport-https aptitude ca-certificates apt-utils software-properties-common docker-ce build-essential libyaml-dev ruby2* libruby2* ruby-bundler rubygems-integration rake; apt-get clean; rm -rf /var/lib/apt/lists/*
          useradd --uid 1000 --home-dir /home/app --create-home --shell /bin/bash app
          groupadd --gid 134 docker-extra
          adduser app docker-extra
          adduser app docker
          chown -R app /home/app
          sudo -u app bash -c 'bundle config set --local path /home/app/vendor/bundle && bundle config set --local jobs 4 && bundle config set --local retry 3 && bundle config set --local deploment true && bundle config set --local without development && bundle install'
          sudo --preserve-env=SSH_AUTH_SOCK -u app /home/app/current/bin/polly build

          echo END bootstrap
    docker:
    - image: cimg/base:2020.07-20.04
      user: root
  primary:
    environment:
      BUNDLE_PATH: "~/vendor/bundle"
    working_directory: "/home/app/current"
    steps:
    - checkout
    - run:
        name: primary
        command: |2

          echo BEGIN rspec
          bundle exec rspec

          echo END rspec
    docker:
    - image: polly:latest
