workflows:
  version: 2
  build:
    jobs:
      - primary

defaults: &defaults
  working_directory: /home/app/current
  environment: &environment_defaults
    CUSTOM: "settings"
  docker:
    - image: &build_image polly:latest

version: 2
jobs:
  primary:
    <<: *defaults
    steps:
      - run:
          name: rspec
          command: |
            whoami
            ls -la
            pwd
            ruby -v
            bundle exec rspec
