workflows:
  version: 2
  build:
    jobs:
      - primary

defaults: &defaults
  working_directory: /home/app/current
  environment: &environment_defaults
    CUSTOM: "settings"
  docker:
    - image: &build_image ubuntu:bionic-20180526

version: 2
jobs:
  primary:
    <<: *defaults
    steps:
      - run:
          name: rspec
          command: |
            bundle exec rspec
