#generated via: polly generate --mirror=circleci --registry=ghcr.io/unhookd > .circleci/config.yml
---
workflows:
  version: 2
  polly:
    jobs:
    - primary:
        requires: []
version: 2
jobs:
  primary:
    working_directory: "/home/app/polly"
    steps:
    - checkout
    - run:
        name: primary
        command: |-
          bundle config set --local path vendor/bundle
          bundle install
          bundle exec rspec
          polly help
    docker:
    - image: ghcr.io/unhookd/polly:4.0-rc-3
