#!/usr/bin/env ruby
  
@bootstrap = image {
  stage "bootstrap", "polly:latest"

  run %q{echo static build}
}

@plain_workflow = Plan.new
@plain_workflow.add_circleci_job("bootstrap",
[{"image"=>"polly:latest","user"=>"root"}],
[{"run"=>{"name"=>"bootstrap","command"=>"
echo static build
"}}],{},"/home/app")
