#!/usr/bin/env ruby
  
@bootstrap_artifact = image {
  stage "bootstrap", "polly:latest"

  run %q{echo static build}
}

@plain_workflow = plan {
  job(
    "bootstrap",
    [{"image"=>"polly:latest","user"=>"root"}],
    [{"run"=>{"name"=>"bootstrap","command"=>"
      echo static build
    "}}],{},"/home/app"
  )
}

@gitch_pipeline = continuous {
  test @plain_workflow
}
