name: primary

on: [push]

jobs:

  build:

    runs-on: ubuntu-20.04

    container:
      image: ubuntu:focal-20200606
      options: "--user 0"

    steps:
    - uses: actions/checkout@v1
    - name: bootstrap
      run: |
        set -e

        export SSH_AUTH_SOCK=/tmp/ssh-auth.sock
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null

        #ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

        bash bin/github-actions.sh
