name: primary

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: bootstrap
      run: |
        set -e

        sudo bash bin/bootstrap.sh

    - name: rspec
      run: |
        set -e

        bundle install --path=vendor/bundle

        bundle exec rspec

        ./bin/polly version
