name: primary

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-20.04
 
    steps:
    - uses: actions/checkout@v1
    - name: bootstrap
      run: |
        set -e

        sudo bash bin/github-actions.sh
