name: primary

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v1
    - name: bootstrap
      run: |
        set -e

        #NOTE: this is here for msodbcsql17 package
        export ACCEPT_EULA=Y
        apt-cache rdepends msodbcsql17 #NOTE: where does this dep come from??

        sudo bash bin/bootstrap.sh

    - name: rspec
      run: |
        set -e

        bundle install --path=vendor/bundle

        bundle exec rspec

        ./bin/polly version
